### ISSUE TITLE
Add a repo description

### ISSUE THREAD

**Issue by gbinal** [GSA/eBuyApi#3]
When you have a moment, it'll be great to add a few words to the repo description so folks have a sense of what this project is.  :)

![screen shot 2017-09-20 at 3 38 46 pm](https://user-images.githubusercontent.com/633088/30663818-dafaa9d0-9e19-11e7-9b56-ad4686b3a7b1.png)

**Comment by nickvasilyev** [comment]
Thanks Gary, definitely was planning to work that in along with a better readme file for this repo and ebuy express.

**Comment by mlsmithGSA** [comment]
Done
